"""
Creates tasks/projects/{task_id}.md files for large handoffs with acceptance criteria.

Only creates files for handoffs that have non-empty acceptance_criteria lists.
Skips if file already exists (idempotent).
"""

import os
import re
import logging
from datetime import date

logger = logging.getLogger(__name__)

PROJECTS_DIR = "tasks/projects"


def create_project_files(meeting_data: dict) -> int:
    """Create project files for large handoffs. Returns count of files created."""
    os.makedirs(PROJECTS_DIR, exist_ok=True)

    created = 0
    session_name = _session_basename(meeting_data)
    session_date = meeting_data.get("session_date", date.today().isoformat())

    for h in meeting_data.get("handoffs", []):
        criteria = h.get("acceptance_criteria", [])
        if not criteria:
            continue  # Small items only

        task_id = h.get("task_id", "").strip()
        if not task_id:
            # Generate a slug from title
            title = h.get("title", "untitled")
            task_id = "handoff-" + re.sub(r"[^a-z0-9]+", "-", title.lower()).strip("-") + f"-{session_date.replace('-', '')}"

        filepath = os.path.join(PROJECTS_DIR, f"{task_id}.md")
        if os.path.exists(filepath):
            logger.info(f"Project file already exists, skipping: {filepath}")
            continue

        content = _render_project_file(h, task_id, session_name, session_date)
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(content)

        logger.info(f"Created project file: {filepath}")
        created += 1

    return created


def _render_project_file(h: dict, task_id: str, session_name: str, session_date: str) -> str:
    assigned_to = h.get("assigned_to", "team")
    priority = h.get("priority", "medium")
    due_date = h.get("due_date") or ""
    title = h.get("title", task_id)
    context = h.get("context", "")
    criteria = h.get("acceptance_criteria", [])
    created_by = h.get("created_by", "meeting-secretary-bot")
    status = h.get("status", "open")

    criteria_rows = "\n".join(
        f"| {c} | Pending |" for c in criteria
    )

    return f"""---
date: "{session_date}"
author: "Meeting Secretary Bot"
model: "secretary-bot-v1"
version: "v1.0"
status: "{status}"
source_session: "{session_name}"
---

# {title}

**ID**: {task_id}
**Assigned to**: {assigned_to}
**Priority**: {priority}
**Due date**: {due_date}
**Status**: {status}
**Created by**: {created_by}
**Source**: {session_name}

## Context

{context}

## Acceptance Criteria

| Criterion | Status |
|-----------|--------|
{criteria_rows}

## Notes

_Auto-generated by Meeting Secretary Bot from `{session_name}.md`_

---
*Generated by: Meeting Secretary Bot | Model: secretary-bot-v1*
*Last Updated: {session_date}*
"""


